// client2/src/AbstractFlash.svelte
{#if message}
  <div class="flex center">
    <div class="hidden-sm"></div>

    <div class='full third-1000'>
      <div class={getCssClass()}>
        <footer>
          {@html message}
        </footer>
        <button class="close icon" type="button" on:click={handleClose}>×</button>
      </div>
    </div>

    <div class="hidden-sm"></div>
  </div>
{/if}

<script>
  import { onMount, onDestroy } from 'svelte';
  import { getEventName } from './flash';

  export let name
  export let addtionalCssClass
  export let message

  const getCssClass = () => {
    var cssClasses = ['card', addtionalCssClass];

    return cssClasses.join(' ');
  }

  const handleClose = () => {
    message = null;
  }

  onMount(() => {
    // listen on global event so we can use `NoticeFlash.show('hello')`
    document.addEventListener(getEventName(name), handleEvent, false);
  })

  onDestroy(() => {
    document.removeEventListener(getEventName(name), handleEvent, false);
  })

  const handleEvent = (e) => {
    message = e.detail.message;
  }

  // const show = (message) => {
  //   const e = new CustomEvent(getEventName(), { detail: { message: message } });
  //   document.dispatchEvent(e);
  // }
  //
  // const clear = () => {
  //   const e = new CustomEvent(getEventName(), { detail: { message: null } });
  //   document.dispatchEvent(e);
  // }
</script>

// app/javascript/components/abstract_flash.jsx
import React from 'react';

class AbstractFlash extends React.Component {
  constructor(props, context) {
    super(props, context);

    this.state = { message: props.message };
  }

  render () {
    if (!this.state.message) {
      return null;
    }

    return (
      <div className="row">
        <div className="col-md-4 col-md-offset-4">
          <div className={this.getCssClass()}>
            <button className="close" type="button" onClick={this.handleClose.bind(this)}>×</button>
            <div dangerouslySetInnerHTML={{ __html: this.state.message }} />
          </div>
        </div>
      </div>
    );
  }

  getCssClass() {
    var cssClasses = ['alert', 'alert-dismissible', this.getAdditionalCssClass()];

    return cssClasses.join(' ');
  }

  handleClose() {
    this.setState({ message: null });
  }

  componentDidMount() {
    // listen on global event so we can use `NoticeFlash.show('hello')`
    $(document).on(this.constructor.getEventName(), (e, data) => {
      this.setState({ message: data.message });
    });
  }

  componentWillUnmount() {
    $(document).off(this.constructor.getEventName());
  }

  getAdditionalCssClass() {
  }

  getName() {
  }

  static getEventName() {
    return 'mykonote.flash.' + this.prototype.getName();
  }

  static show(message) {
    $(document).trigger(this.getEventName(), { message: message });
  }
}

export default AbstractFlash;
