// client/src/NoteForm.svelte
<div class:hidden-sm={!showForm}>
  <form
    bind:this={formContainerElement}
    on:submit={handleFormSubmit}>

    <input
      type="text"
      value={note.title}
      on:input={handleTitleChange}
      placeholder="Title"
      bind:this={titleElement}
    />

    <div bind:this={contentContainerElement}></div>
  </form>
</div>

<script>
  import { createEventDispatcher, onMount, onDestroy, afterUpdate } from 'svelte'
  import './highlight.js'
  import Quill from 'quill'
  import 'quill-task-list/task_list_node'
  import 'quill/dist/quill.snow.css'
  import EventHive from './EventHive'

  export let note
  export let showForm

  const dispatch = createEventDispatcher()

  let shouldRerender = true
  let editor
  let formContainerElement
  let titleElement
  let contentContainerElement
  let contentElement
  let noteUpdateSubscription

  // prevent form submission by hitting enter.
  // changes will be asynchronously saved by ajax.
  const handleFormSubmit = (e) => {
    e.preventDefault()
    return false
  }

  const handleTitleChange = () => {
    shouldRerender = true
    note.title = titleElement.value
    dispatch('change', note)    
  }

  const handleContentChange = () => {
    shouldRerender = false
    note.content = contentElement.innerHTML
    dispatch('change', note)    
  }

  const renderEditor = () => {
    editor = new Quill(contentContainerElement, {
      theme: 'snow',
      modules: {
        'syntax': true,
        'toolbar': [
          [{ 'header': [1, 2, false] }],
          ['bold', 'italic', 'strike'],
          [{ 'color': [] }, { 'background': [] }],
          ['blockquote', 'code-block'],
          [
            { 'list': 'ordered' }, { 'list': 'bullet' }, 'task-list',
            { 'indent': '-1' }, { 'indent': '+1' }
          ],
          ['link', 'image'],
          ['clean']
        ],
        'task-list': true
      }
    })

    contentElement = contentContainerElement.querySelector('.ql-editor')
  }

  const focusTitleFieldIfNewNote = () => {
    if (note.isNew()) {
      setTimeout(() => titleElement.focus(), 100)
    }
  }

  onMount(() => {
    renderEditor()

    // when updating the note from outside (e.g. from the mobile app), in which
    // case a sync to the server should be triggered. if we just use the react
    // eventing the rte won't detect the changes.
    noteUpdateSubscription = EventHive.subscribe('note.update', (data) => {
      titleElement.value = data.title
      handleTitleChange()
      editor.pasteHTML(data.content)
    })
  })

  // gets called initially and when a note is switched
  afterUpdate(() => {
    // don't rerender if the RTE content changes. the cursor jumps to the
    // beginning of the content if we re-initialize the RTE content.
    if (shouldRerender) {
      editor.off('text-change')
      // reset the content before inserting the actual content.
      // presumably because of change tracking (delta stuff) in quill the
      // insertion of big content hangs the browser for several seconds.
      editor.setText('')
      contentElement.innerHTML = note.content
      // wait on updates so the state of the editor is up to date for clearing
      // the history and attaching events
      editor.update()
      editor.history.clear()
      editor.on('text-change', handleContentChange)
    }
  })

  onDestroy(() => {
    noteUpdateSubscription.remove()
  })

  let previousNoteUid
  $: {
    // a different note is shown.
    if (titleElement && note.uid !== previousNoteUid) {
      previousNoteUid = note.uid
      shouldRerender = true
      focusTitleFieldIfNewNote()
    }
  }
</script>

<style lang="sass">
  :global
    @import './stylesheets/quill.snow.custom'
    @import 'quill-task-list/task_list'
</style>

// app/javascript/components/note_form.jsx
import React from 'react';

class NoteForm extends React.Component {
  constructor(props, context) {
    super(props, context);

    this.state = {
      note: this.props.note
    };

    this.shouldRerender = true;
  }

  render() {
    return (
      <form
        className="form-horizontal"
        ref={(c) => this.$formContainer = $(c)}
        onSubmit={this.handleFormSubmit}>
        <div className="form-inputs">
          <div className="form-group form-group-no-label string optional">
            <input
              type="text"
              className="string optional form-control"
              value={this.state.note.title}
              onChange={this.handleTitleChange.bind(this)}
              placeholder="Title"
              ref={(c) => this.$title = $(c)}
            />
          </div>
          <div className="form-group form-group-no-label text optional">
            <div
              ref={(c) => this.$contentContainer = $(c)}
            ></div>
          </div>
        </div>
      </form>
    );
  }

  // prevent form submission by hitting enter.
  // changes will be asynchronously saved by ajax.
  handleFormSubmit(e) {
    e.preventDefault();
    return false;
  }

  handleTitleChange() {
    this.shouldRerender = true;
    this.state.note.title = this.$title.val();
    this.setState({ note: this.state.note }, this.handleChange);
  }

  handleContentChange() {
    this.shouldRerender = false;
    this.state.note.content = this.$content.html();
    this.setState({ note: this.state.note }, this.handleChange);
  }

  handleChange() {
    this.props.handleChange(this.state.note);
  }

  componentDidMount() {
    this.focusTitleFieldIfNewNote();
    this.renderEditor();

    // when updating the note from outside (e.g. from the mobile app), in which
    // case a sync to the server should be triggered. if we just use the react
    // eventing the rte won't detect the changes.
    EventHive.subscribe('note.update', (data) => {
      this.$title.val(data.title);
      this.handleTitleChange();
      this.editor.pasteHTML(data.content);
    });

    if (ViewportMode.isMobileMode()) {
      EventHive.subscribe('hamburger.show', () => {
        this.$formContainer.addClass('hidden');
      });
      EventHive.subscribe('hamburger.hide', () => {
        this.$formContainer.removeClass('hidden');
      });

      EventHive.subscribe('search.entered', () => {
        this.$formContainer.addClass('hidden');
      });
    }
  }

  // gets called initially and when a note is switched
  componentDidUpdate() {
    this.editor.off('text-change');
    // reset the content before inserting the actual content.
    // presumably because of change tracking (delta stuff) in quill the
    // insertion of big content hangs the browser for several seconds.
    this.editor.setText('');
    this.$content.html(this.state.note.content);
    this.editor.history.clear();
    // wait on updates before attaching the `text-change` event
    this.editor.update();
    this.editor.on('text-change', this.handleContentChange.bind(this));
  }

  componentWillReceiveProps(nextProps) {
    // a different note is shown.
    if (nextProps.note.uid !== this.state.note.uid) {
      this.shouldRerender = true;
      this.setState({
        note: nextProps.note
      }, () => this.focusTitleFieldIfNewNote());
    }
  }

  shouldComponentUpdate(nextProps, nextState) {
    // don't rerender if the RTE content changes. the cursor jumps to the
    // beginning of the content if we re-initialize the RTE content.
    return this.shouldRerender;
  }

  renderEditor() {
    this.editor = new Quill(this.$contentContainer.get(0), {
      theme: 'snow',
      modules: {
        'syntax': true,
        'toolbar': [
          [{ 'header': [1, 2, false] }],
          ['bold', 'italic', 'strike'],
          [{ 'color': [] }, { 'background': [] }],
          ['blockquote', 'code-block'],
          [
            { 'list': 'ordered' }, { 'list': 'bullet' }, 'task-list',
            { 'indent': '-1' }, { 'indent': '+1' }
          ],
          ['link', 'image'],
          ['clean']
        ],
        'task-list': true
      }
    });

    this.$content = this.$contentContainer.find('.ql-editor');
  }

  focusTitleFieldIfNewNote() {
    if (this.state.note.isNew()) {
      this.$title.focus();
    }
  }
}

export default NoteForm;
