// client/src/SaveStateLabel.svelte
{#if isSynced}
  <div class="save-state saved">Saved</div>
{:else}
  <div class="save-state saving">Saving</div>
{/if}

<script>
  let { isSynced } = $props();
</script>

<style lang="sass">
  @import './stylesheets/variables'

  .save-state
    font-size: $font-size-sm
    text-transform: uppercase

    &.saved
      color: $picnic-success

    &.saving
      color: $picnic-warning
</style>

// app/javascript/components/save_state_label.jsx
import React from 'react';

class SaveStateLabel extends React.Component {
  constructor(props, context) {
    super(props, context);

    this.state = { isSynced: props.isSynced };
  }

  componentWillReceiveProps(nextProps) {
    this.setState({ isSynced: nextProps.isSynced });
  }

  render () {
    return (
      <div className="save-state">
        {
          this.state.isSynced
            ?
            <div className="label label-success">Saved</div>
            :
            <div className="label label-warning">Saving</div>
        }
      </div>
    );
  }
}

export default SaveStateLabel;
